apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.kubernetes.com
  labels:
    app: helloworld
spec:
  containers:
  - name: kubernetes-demo
    image: sridhb/helloworld-kubernetes
    ports:
    - name: nodejs-port
      containerPort: 3000
